# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_restore_terminals_fix
project_short_description: Jupyterlab fix in a form of extension for a common problem
    of restoring workspace after server restart etc... such that terminal windows
    are there, but they all were opened in the same location (notebook root). We'd
    like to have them opened in the locations where they were opened originally.
python_name: jupyterlab_restore_terminals_fix
repository: ''
test: true

